### ISSUE TITLE
Tests won't run: xxx

### ISSUE THREAD

**Issue by diskostu** [gwt-test-utils/gwt-test-utils#100]
I'm on GWT 2.9.0 with JDK 11.

Whenever I launch a test, I get:
```java
C:\DEV\paas\java\jdk-11.0.9+11\bin\java.exe

com.googlecode.gwt.test.exceptions.GwtTestPatchException: Error while scanning package 'com.googlecode.gwt.test.internal.patchers'

	at com.googlecode.gwt.test.internal.ClassesScanner.scanPackages(ClassesScanner.java:65)
	at com.googlecode.gwt.test.internal.ConfigurationLoader.visitPatchClasses(ConfigurationLoader.java:281)
	at com.googlecode.gwt.test.internal.ConfigurationLoader.<init>(ConfigurationLoader.java:55)
	at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:99)
	at com.googlecode.gwt.test.internal.GwtFactory.initializeIfNeeded(GwtFactory.java:54)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:27)
	at com.googlecode.gwt.test.GwtRunner.<init>(GwtRunner.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: com.googlecode.gwt.test.exceptions.GwtTestPatchException: Cannot find class in the classpath : 'com.googlecode.gwt.test.internal.patchers.JSONParserPatcher'
	at com.googlecode.gwt.test.internal.GwtClassPool.getClass(GwtClassPool.java:25)
	at com.googlecode.gwt.test.internal.ClassesScanner.visitClass(ClassesScanner.java:104)
	at com.googlecode.gwt.test.internal.ClassesScanner.scanClassesFromJarFile(ClassesScanner.java:96)
	at com.googlecode.gwt.test.internal.ClassesScanner.scanPackages(ClassesScanner.java:59)
	... 20 more


Process finished with exit code -1
```
Is this something related to GWT 2.9.0, which you currently don't officially support, or is it something else?

**Comment by krichter722** [comment]
I worked around this by making `JSONParserPatcher` public and using my own build of 0.64-SNAPSHOT. This patch is a viable candidate for a PR. However I'd like to figure out why the build doesn't fail currrently (https://www.travis-ci.org/github/gwt-test-utils/gwt-test-utils).
