### ISSUE TITLE
com.googlecode.gwt.test.exceptions.GwtTestConfigurationException: Error while parsing GWT module 'com.erc.module.MyModule' : gwt-test-utils compatibility with GWT 2.10.0 and Java 11 

### ISSUE THREAD

**Issue by raghubhogireddy** [gwt-test-utils/gwt-test-utils#106]
Hello There, 

I assume, Currently, there is no official statement whether gwt-test-utils works with `GWT 2.10.0 & Java 11` or not . 

In our GWT Applications, we have tests written `@GwtModule` which Specify the GWT module to test in a `GwtModuleRunner.`
We have migrated to below Configuration now. Previously it was `GWT 2.6 & Java 1.8`
Present it was `GWT 2.10.0 & Java 11`. 

when we ran our tests we are getting below error StackTrace:

        
	com.googlecode.gwt.test.exceptions.GwtTestConfigurationException: Error while parsing GWT module 'com.erc.module.MyModule'
        com.googlecode.gwt.test.internal.ModuleData.parseModule(ModuleData.java:291)
	at com.googlecode.gwt.test.internal.ModuleData.<init>(ModuleData.java:121)
	at com.googlecode.gwt.test.internal.ModuleData.get(ModuleData.java:101)
	at com.googlecode.gwt.test.internal.GwtConfig.setupInstance(GwtConfig.java:106)
	at com.googlecode.gwt.test.GwtTest.<init>(GwtTest.java:72)
        at com.googlecode.gwt.test.GwtTestWithMocks.<init>(GwtTestWithMocks.java:50)
	at com.googlecode.gwt.test.GwtTestWithMockito.<init>(GwtTestWithMockito.java:28)
	at com.erc.module.MyModule.MyModuleTest.<init>(MyModuleTest.java:40)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.googlecode.gwt.test.internal.junit.GwtBlockJUnit4ClassRunner.run(GwtBlockJUnit4ClassRunner.java:25)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.run(AbstractGwtRunner.java:44)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
        Caused by: org.apache.xml.dtm.DTMConfigurationException: No default implementation found 
	at org.apache.xml.dtm.DTMManager.newInstance(DTMManager.java:142)
	at org.apache.xpath.XPathContext.<init>(XPathContext.java:102)
	at org.apache.xpath.jaxp.XPathImpl.eval(XPathImpl.java:207)
	at org.apache.xpath.jaxp.XPathImpl.evaluate(XPathImpl.java:281)
	at com.googlecode.gwt.test.internal.ModuleData.initializeInherits(ModuleData.java:215)
	at com.googlecode.gwt.test.internal.ModuleData.parseModuleFile(ModuleData.java:308)
	at com.googlecode.gwt.test.internal.ModuleData.initializeInherits(ModuleData.java:227)
	at com.googlecode.gwt.test.internal.ModuleData.parseModuleFile(ModuleData.java:308)
	at com.googlecode.gwt.test.internal.ModuleData.initializeInherits(ModuleData.java:227)
	at com.googlecode.gwt.test.internal.ModuleData.parseModuleFile(ModuleData.java:308)
	at com.googlecode.gwt.test.internal.ModuleData.parseModule(ModuleData.java:283)
	... 38 more
         Caused by: com.googlecode.gwt.test.exceptions.GwtTestPatchException: Error while defining 
         jdk.internal.reflect.ConstructorAccessorImpl from modified bytecode
	at com.googlecode.gwt.test.internal.GwtClassLoader.findClass(GwtClassLoader.java:192)
	at javassist.Loader.loadClass(Loader.java:350)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1194)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.xml.dtm.ObjectFactory.createObject(ObjectFactory.java:143)
	at org.apache.xml.dtm.ObjectFactory.createObject(ObjectFactory.java:103)
	at org.apache.xml.dtm.DTMManager.newInstance(DTMManager.java:137)
	... 48 more
        Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by 
       com.googlecode.gwt.test.internal.GwtClassLoader$GwtClassLoaderWithRewriter @13e12738 cannot access jdk/internal/reflect 
        superclass jdk.internal.reflect.MagicAccessorImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.googlecode.gwt.test.internal.GwtClassLoader.findClass(GwtClassLoader.java:187)
	... 65 more
        com.googlecode.gwt.test.exceptions.GwtTestException: Because of the single-threaded nature of the GWT environment, gwt- 
         test-utils tests can not be run in multiple thread at the same time

	at com.googlecode.gwt.test.internal.GwtConfig.setupInstance(GwtConfig.java:101)
	at com.googlecode.gwt.test.GwtTest.<init>(GwtTest.java:72)
	at com.googlecode.gwt.test.GwtTestWithMocks.<init>(GwtTestWithMocks.java:50)
	at com.googlecode.gwt.test.GwtTestWithMockito.<init>(GwtTestWithMockito.java:28)
	at com.erc.module.MyModule.MyModuleTest.<init>(MyModuleTest.java:40)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.googlecode.gwt.test.internal.junit.GwtBlockJUnit4ClassRunner.run(GwtBlockJUnit4ClassRunner.java:25)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.run(AbstractGwtRunner.java:44)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)`

**Comment by nbartels** [comment]
Please check my repository and the special branch: https://github.com/nbartels/gwt-test-utils/tree/java11-gwt-2.10.0

**Comment by raghubhogireddy** [comment]
Hi @nbartels, Thanks for the addressing the issue. 

**Do we have any timelines finalized, for this `0.65` release of `gwt-test-utils` ?**  which supports GWT 2.10.0 and Java 11. Currently, this version was yet to be released I believe. 

I have used this jar and tested out the UTCs. I got the below ErrorStackTrace:


`   
    java.lang.UnsupportedOperationException: NestMember requires ASM7
    at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
    at com.googlecode.gwt.test.internal.rewrite.OverlayTypesRewriter.rewrite(OverlayTypesRewriter.java:565)
    at com.googlecode.gwt.test.internal.GwtClassLoader$GwtClassLoaderWithRewriter.findClassBytes(GwtClassLoader.java:90)
    at com.googlecode.gwt.test.internal.GwtClassLoader.findClass(GwtClassLoader.java:170)
    at javassist.Loader.loadClass(Loader.java:350)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.getDeclaredFields0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
    at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
    at org.junit.runners.model.TestClass.getSortedDeclaredFields(TestClass.java:77)
    at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:70)
    at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
    at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:111)
    at org.junit.runners.ParentRunner.<init>(ParentRunner.java:91)
    at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
    at com.googlecode.gwt.test.internal.junit.GwtBlockJUnit4ClassRunner.<init>(GwtBlockJUnit4ClassRunner.java:18)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.googlecode.gwt.test.internal.junit.AbstractGwtRunnerFactory.newInstance(AbstractGwtRunnerFactory.java:62)
    at com.googlecode.gwt.test.internal.junit.AbstractGwtRunnerFactory.create(AbstractGwtRunnerFactory.java:40)
    at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:28)
    at com.googlecode.gwt.test.GwtRunner.<init>(GwtRunner.java:18)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
    at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
    at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
    at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
`
 

At a high level, I could understand this was something related to ClassVisitor and it checks for ASM version compatibility. 
while having a close look at the jar sources, I could see there are couple of usages related  `OpCodes.ASM5` in classes 
 inside `com.googlecode.gwt.test.internal.rewrite` packages. I have made changes to from `OpCodes.ASM5` -> `OpCodes.ASM7` and now my tests are getting passed.
