### ISSUE TITLE
Error while generating gwt-test-utils prerequisites

### ISSUE THREAD

**Issue by georve** [gwt-test-utils/gwt-test-utils#46]
hi, recently i made a migration to gwt 2.5.1 and gwt-test-utils 0.44 but when i run test cases that worked in gwt 2.1 appear the following error in console

com.googlecode.gwt.test.exceptions.GwtTestException: Error while generating gwt-test-utils prerequisites
    at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:113)
    at com.googlecode.gwt.test.internal.GwtFactory.initializeIfNeeded(GwtFactory.java:45)
    at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:30)
    at com.googlecode.gwt.test.GwtRunner.<init>(GwtRunner.java:19)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
    at com.google.gwt.dev.cfg.ModuleDef.checkForSeedTypes(ModuleDef.java:580)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:376)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:367)
    at com.googlecode.gwt.test.internal.GwtFactory.createCompilationState(GwtFactory.java:151)
    at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:106)
    ... 21 more

**Comment by jzaruba** [comment]
0.53 w/ GWT 2.8.1
also the exception is not very revealing :(

**Comment by jzaruba** [comment]
So my problem was that with my (otherwise functional) GWT configuration the test was unable to find my module.gwt.xml. I had to add extra `<resource/>` element to `project/build/resources`.

Unfortunately, the exception tells you pretty much nothing. I can see some `CompilationProblemReporter.logErrorTrace` calls in the code, the output is nowhere to be seen though. (Maybe I should configure something somewhere...?)

My advice for anyone in similar situation would be to tell your debugger to suspend whenever `UnableToCompleteException` is thrown, and then look around that spot:

In IntelliJ Idea you do that by pressing **Ctrl+Shift+F8**:
![screenshot 2017-12-19 20 55 01](https://user-images.githubusercontent.com/6112450/34176149-30a20366-e4ff-11e7-82f0-49d693cb86f7.png)
...and then adding `UnableToCompleteException`

Still, thanks for the effort put into this project, hopefully I can make it work.

Cheers :)

**Comment by ZehnVon12** [comment]
How do you add the module as resource?
