### ISSUE TITLE
Doesn't compile against GWT 2.7

### ISSUE THREAD

**Issue by davido** [gwt-test-utils/gwt-test-utils#68]
Trying to use the latest released 0.47 version failing for Gerrit Code Review, with

```
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   com.google.gerrit.client.diff.EditIteratorTest
FAILURE initializationError: com.google.gwt.dev.javac.CompilationStateBuilder.init(Lcom/google/gwt/core/ext/TreeLogger;Ljava/io/File;)V
java.lang.NoSuchMethodError: com.google.gwt.dev.javac.CompilationStateBuilder.init(Lcom/google/gwt/core/ext/TreeLogger;Ljava/io/File;)V
	at com.googlecode.gwt.test.internal.GwtFactory.createCompilationState(GwtFactory.java:156)
	at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:112)
	at com.googlecode.gwt.test.internal.GwtFactory.initializeIfNeeded(GwtFactory.java:46)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:30)
	at com.googlecode.gwt.test.GwtRunner.<init>(GwtRunner.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runner.Computer.getRunner(Computer.java:38)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:98)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:84)
	at org.junit.runners.Suite.<init>(Suite.java:79)
	at org.junit.runner.Computer.getSuite(Computer.java:26)
	at com.facebook.buck.junit.JUnitRunner.run(JUnitRunner.java:134)
	at com.facebook.buck.junit.Main.main(Main.java:102)
```

**Comment by JamesXNelson** [comment]
@davido -> Myself and some colleagues from Appian have implemented support for Gwt 2.7 in gwt-test-utils.
https://github.com/gwt-test-utils/gwt-test-utils/pull/69

We will be deploying a jar to our private nexus so we can run our test cases against it.  We recommend you do the same, and if you come across any unpatched methods, feel free to patch / add bug reports.

Thanks!

**Comment by retomerz** [comment]
Ping - Any news ?

**Comment by JamesXNelson** [comment]
He merged in the PR we use at work.  There is one lingering bug he said we would fix as well.

We deployed the same version that is in master here to our local nexus and it works perfectly.

**Comment by msurkein** [comment]
Any chance we could get the new version pushed to maven central?

**Comment by JamesXNelson** [comment]
In case @Gael is unable to tend to a release, you could either push to your own nexus / artifactory, or if you do not have one, it is possible to release a version to maven central under a different groupId.  I do push to central under net.wetheinter, but I would not want to deploy someone else's artifacts as it would look a lot like stealing.

Perhaps if you could check out the project, build it locally and verify that it works with your tests, Gael could have more confidence that it is ready to push to central?

**Comment by gorshkov-leonid** [comment]
Hi, what the expected release date of 0.48?

**Comment by JamesXNelson** [comment]
@gorshkov-leonid -> If you want to check out the source, build and run your tests locally, and if they pass, I could probably push this to maven central for you under a different groupId.

Do you have your own nexus that you could deploy to?  I would hate to pollute central with a temporary workaround jar, but I will if it helps you.

**Comment by gorshkov-leonid** [comment]
Thanks, we have published library to nexus. Licence allows build from sources and publishing.

**Comment by feedm3** [comment]
To a public nexus? If so, could you please post the link?

**Comment by JamesXNelson** [comment]
Well, if Gael is going to be too busy, should the next version of Gwt be lacking in support, I would be happy to patch it as well to keep this library up and running.

**Comment by jfrantzius** [comment]
Thanks @JamesXNelson , got it to work with GWT 2.7 by compiling gwt-test-utils from master.

**Comment by olgagrinberg** [comment]
Hi,
is the workaround for GWT 2.7 available in maven central ?
Thanks

**Comment by Gael** [comment]
Hi,

gwt-test-utils 0.51 for GWT 2.7 is now available on maven central : http://repo1.maven.org/maven2/com/googlecode/gwt-test-utils/gwt-test-utils/0.51/

Any feedback would be appreciated ;)
