### ISSUE TITLE
GWT UNIT TEST- GWT-TEST-UTILS

### ISSUE THREAD

**Issue by jyothiswarupad** [gwt-test-utils/gwt-test-utils#72]
Hi,

I am new to GWT concept.Now I am working on Unit test cases for GWT- Client side for button action events. Whenever i'm trying to run the test cases i have found an issue like Initialization error. i.e.,
java.lang.NoSuchMethodError: com.google.gwt.dev.javac.CompilationStateBuilder.init(Lcom/google/gwt/core/ext/TreeLogger;Ljava/io/File;)V
    at com.googlecode.gwt.test.internal.GwtFactory.createCompilationState(GwtFactory.java:156)
    at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:112)
    at com.googlecode.gwt.test.internal.GwtFactory.initializeIfNeeded(GwtFactory.java:46)
    at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:30)

I have used GWT -2.6.0 version  and gwt-test-utils-0.47.

Please provide your valuable Solutions.

Thanks in Advance

**Comment by jyothiswarupad** [comment]
Hi,

Any update on this?

**Comment by Gael** [comment]
Did you try to update to the lastest version of GWT (2.8.2) and gwt-test-utils (0.60) ?
It should work well.
