### ISSUE TITLE
GWT-Client Unit Testing

### ISSUE THREAD

**Issue by jyothiswarupad** [gwt-test-utils/gwt-test-utils#73]
Hi,

I'm New to GWT. Now working on GWT client side unit testing. So far, faced initilization error while executing the test class. So, finally adding GWT 2.3 jar and GWt-Utils 0.35 got rid of that original issue.
Now it seems to be asking me to create a field and faced some issue in test method.. i.e,

java.lang.ClassFormatError: Duplicate method name&signature in class file com/google/gwt/user/client/ui/ComplexPanel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at javassist.Loader.findClass(Loader.java:379)
	at javassist.Loader.loadClass(Loader.java:311)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at javassist.Loader.findClass(Loader.java:379)
	at javassist.Loader.loadClass(Loader.java:311)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.octo.gwt.test.internal.handlers.DockLayoutPanelHandler.create(DockLayoutPanelHandler.java:24)
	at com.octo.gwt.test.internal.patchers.GwtPatcher.create(GwtPatcher.java:22)
	at com.google.gwt.core.client.GWT.create(GWT.java)
	at com.google.gwt.user.client.ui.UIObject.<clinit>(UIObject.java:195)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at com.octo.gwt.test.utils.GwtReflectionUtils.setStaticField(GwtReflectionUtils.java:441)
	at com.octo.gwt.test.internal.GwtConfig.setupDebugIdImpl(GwtConfig.java:155)
	at com.octo.gwt.test.internal.GwtConfig.setupInstance(GwtConfig.java:169)
	at com.octo.gwt.test.internal.GwtConfig.setup(GwtConfig.java:48)
	at com.octo.gwt.test.GwtTest.setUpGwtTest(GwtTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.octo.gwt.test.internal.runner.AbstractGwtRunner.run(AbstractGwtRunner.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

com.octo.gwt.test.exceptions.ReflectionException: Unable to find field, class 'class com.google.gwt.user.client.Timer', fieldName 'timers'
	at com.octo.gwt.test.utils.GwtReflectionUtils.getUniqueFieldByName(GwtReflectionUtils.java:534)
	at com.octo.gwt.test.utils.GwtReflectionUtils.getStaticFieldValue(GwtReflectionUtils.java:291)
	at com.octo.gwt.test.GwtReset.getStaticAndCallClear(GwtReset.java:30)
	at com.octo.gwt.test.GwtReset.reset(GwtReset.java:38)
	at com.octo.gwt.test.GwtTest.tearDownGwtTest(GwtTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.octo.gwt.test.internal.runner.AbstractGwtRunner.run(AbstractGwtRunner.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

So could you please help me for resolving the above issue.

I have used JUnit- Eclipse Kepler.

Thanks in advance

**Comment by JamesXNelson** [comment]
Not sure why you would want to run on GWT 2.3.

Updating to 2.7 and using the latest versions will be much, much easier for you in the long run.

**Comment by Gael** [comment]
Hi, 

If you want to use GWT 2.3.0, you''ll have to use the 0.33.4 version according to the [gwt compatibilty page](https://github.com/gwt-test-utils/gwt-test-utils/wiki/GWT-compatibility)
