### ISSUE TITLE
java.lang.AssertionError: Cannot dispatch 'blur' event : the targeted element has to be enabled

### ISSUE THREAD

**Issue by maciej-nowicki** [gwt-test-utils/gwt-test-utils#93]
After upgrading to latest version I get following error:

`java.lang.AssertionError: Cannot dispatch 'blur' event : the targeted element has to be enabled : <button type="button" class="gwt-ButtonSmall" title="Show next page (2 results )" disabled=""><img src="images/right-disabled.png"></img></button>
	at com.googlecode.gwt.test.GwtTest$1.onError(GwtTest.java:45)
	at com.googlecode.gwt.test.GwtModuleRunnerAdapter$BrowserErrorHandlerDelegate.onError(GwtModuleRunnerAdapter.java:40)
	at com.googlecode.gwt.test.utils.events.Browser.canApplyEvent(Browser.java:1343)
	at com.googlecode.gwt.test.utils.events.Browser.canApplyEvent(Browser.java:1330)
	at com.googlecode.gwt.test.utils.events.Browser.dispatchEventsInternal(Browser.java:1455)
	at com.googlecode.gwt.test.utils.events.Browser.dispatchEvent(Browser.java:449)
	at com.googlecode.gwt.test.utils.events.Browser.clickInternal(Browser.java:1367)
	at com.googlecode.gwt.test.utils.events.Browser.click(Browser.java:224)
	at com.googlecode.gwt.test.utils.events.Browser.click(Browser.java:219)
(...)`

To fix this additional check before applying the event is required

**Comment by nbartels** [comment]
The problem is, that there are more events that cannot be dispatched if the element is disabled. All the mouse events for example. So your change from your PR solves the specific problem, but then you run into one of the mouse problems. I tried to solve this and realised, that you simply need to add/set the browser error handler. There you receive the error message and can handle it and if you don't need it simply ignore it.

Simply call `setBrowserErrorHandler` in your test class and set your custom error handler. 

Therefore I cannot use that commit from your PR, but I'll have a look at the other commit. This looks more interesting ;)
